# Generated by Django 4.2.4 on 2023-08-21 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_examcenter2_student2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamCenter2',
            new_name='Village',
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
        migrations.CreateModel(
            name='Kas',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.village',),
        ),
        migrations.RenameField(
            model_name='village',
            old_name='centerName',
            new_name='centerName2',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='city',
            new_name='city2',
        ),
    ]
